version: '3.4'

services:
  jekyll:
    build: .
    user: ${JEKYLL_USER:-jekyll}
    command: ${COMMAND:-make run}
    volumes:
      - .:/srv/jekyll
    ports:
      - 3002:3002
      - 3003:3003
    healthcheck:
      test: curl --fail -I localhost:3000
