[[headers]]
  for = "/konnect/*"
  [headers.values]
    Basic-Auth = "docs:CAB-beta-doc"

[[headers]]
  for = "/hub/*"
  [headers.values]
    Basic-Auth = "docs-ee:kongenterpriserc"

[[headers]]
  for = "/enterprise/*"
  [headers.values]
    Basic-Auth = "docs-ee:kongenterpriserc"

[[headers]]
  for = "/getting-started-guide/*"
  [headers.values]
    Basic-Auth = "docs-ee:kongenterpriserc"
