# Site settings
name: Kong by Mashape
domain: localhost:3000
url: http://localhost:9000
repo: https://github.com/Mashape/kong
docrepo: https://github.com/Mashape/getkong.org
documentation: docs

# Build settings

source: app
destination: dist
permalink: pretty
plugins: ./app/_jekyll_plugins
keep_files: ['assets']
timezone: America/San_Francisco
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "no_intra_emphasis", "autolink", "with_toc_data", "strikethrough"," lax_html_blocks", "superscript", "tables"]
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: 'docs'
    values:
      layout: 'docs'
