# Site settings
name: Kong - Open-Source API and Microservice Management Layer
domain: getkong.org
url: http://getkong.org
repo: https://github.com/Mashape/kong
docrepo: https://github.com/Mashape/getkong.org
documentation: docs

# Build settings
source: app
destination: dist
permalink: pretty
plugins: ./app/_jekyll_plugins
keep_files: ['assets']
timezone: America/San_Francisco
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "no_intra_emphasis", "autolink", "with_toc_data", "strikethrough"," lax_html_blocks", "superscript", "tables"]
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'page'
  -
    scope:
      path: 'docs'
    values:
      layout: 'docs'
  -
    scope:
      path: 'plugins'
    values:
      header_btn_text: Report Bug
      header_btn_href: https://github.com/Mashape/kong/issues/new
      header_btn_target: _blank
      id: page-plugin
      breadcrumbs:
        Plugins: /plugins
